-- MySQL Script generated by MySQL Workbench
-- Sat Sep 12 12:34:23 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema caretaker_dev 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caretaker_dev
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `caretaker_dev` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `caretaker_dev` ;

-- -----------------------------------------------------
-- Table `caretaker_dev`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caretaker_dev`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caretaker_dev`.`caretaker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caretaker_dev`.`caretaker` (
  `caretaker_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  `State` VARCHAR(2) NOT NULL,
  `zip` INT NOT NULL,
  `x_coord` FLOAT NOT NULL,
  `y_coord` FLOAT NOT NULL,
  `radius` INT NOT NULL,
  `language` VARCHAR(15) NOT NULL,
  `experience` VARCHAR(15) NOT NULL,
  `location_id` INT NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `google_id` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `can_cook` TINYINT(1) NULL DEFAULT 0,
  `can_clean` TINYINT(1) NULL DEFAULT 0,
  `can_drive` TINYINT(1) NULL DEFAULT 0,
  `skills_explanation` TEXT(500) NULL,
  `bio` TEXT(1000) NULL,
  `price_range` VARCHAR(45) NOT NULL,
  `pets_allowed` TINYINT(1) NULL DEFAULT 0,
  `age` INT NOT NULL,
  `profile_pic` VARCHAR(200),
  PRIMARY KEY (`caretaker_id`),
  INDEX `fk_caretaker_location_idx` (`location_id` ASC),
  CONSTRAINT `fk_caretaker_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `caretaker_dev`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caretaker_dev`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caretaker_dev`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `town` VARCHAR(15) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip` INT NOT NULL,
  `x_coord` FLOAT NOT NULL,
  `y_coord` FLOAT NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `location_id` INT NULL,
  `gender` VARCHAR(10) NULL,
  `profile_pic` VARCHAR(200) NULL,
  `email` VARCHAR(45) NOT NULL,
  `google_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customer_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_customer_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `caretaker_dev`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
